/* Marshrut → tarjima kaliti xaritasi (messages/*.json "RouteLabels" nomspeysi).
   Sidebar (app-sidebar.tsx) navItems/footerItems bilan yagona manba sifatida
   ishlatiladi (breadcrumb ham shu yerdan o'qiydi). */
export const ROUTE_LABEL_KEYS: Record<string, string> = {
  "/dashboard": "home",
  "/dashboard/classes": "myClasses",
  "/dashboard/students": "students",
  "/dashboard/timetable": "timetable",
  "/dashboard/planner": "planner",
  "/dashboard/lessons": "lessons",
  "/dashboard/attendance": "attendance",
  "/dashboard/behavior": "behavior",
  "/dashboard/grades": "grades",
  "/dashboard/grades/help": "gradesHelp",
  "/dashboard/standards": "standards",
  "/dashboard/tasks": "tasks",
  "/dashboard/changelog": "changelog",
  "/dashboard/feedback": "feedback",
  "/dashboard/settings": "settings",
  "/dashboard/cj": "comparativeJudgement",
  "/dashboard/hisobot": "report",
  "/dashboard/ozlashtirish": "mastery",
  "/dashboard/quiz": "quiz",
  "/dashboard/xulosa": "summary",
  "/admin": "admin",
  "/admin/users": "adminUsers",
  "/admin/schools": "adminSchools",
  "/admin/feedback": "adminFeedback",
  "/admin/audit": "adminAudit",
};
