/* Marshrut → tarjima kaliti xaritasi (messages/*.json "RouteLabels" nomspeysi).
   Sidebar (app-sidebar.tsx) navItems/footerItems bilan yagona manba sifatida
   ishlatiladi (breadcrumb ham shu yerdan o'qiydi). */
export const ROUTE_LABEL_KEYS: Record<string, string> = {
  "/dashboard": "home",
  "/dashboard/classes": "myClasses",
  "/dashboard/students": "students",
  "/dashboard/timetable": "timetable",
  "/dashboard/planner": "planner",
  "/dashboard/tasks": "tasks",
  "/dashboard/lessons": "lessons",
  "/dashboard/resources": "resources",
  "/dashboard/attendance": "attendance",
  "/dashboard/behavior": "behavior",
  "/dashboard/grades": "grades",
  "/dashboard/grades/help": "gradesHelp",
  "/dashboard/statistics": "statistics",
  "/dashboard/standards": "standards",
  "/dashboard/changelog": "changelog",
  "/dashboard/feedback": "feedback",
  "/dashboard/settings": "settings",
  "/dashboard/games": "games",
  "/dashboard/games/arqon": "gameArqon",
  "/dashboard/games/poyga": "gamePoyga",
  "/dashboard/games/piyoda-poyga": "gamePiyodaPoyga",
  "/dashboard/games/live-host": "gameLiveHost",
  "/dashboard/games/live-play": "gameLivePlay",
  "/dashboard/games/host": "gameHost",
  "/dashboard/games/xotira": "gameXotira",
  "/dashboard/games/qaysi-katta": "gameQaysiKatta",
  "/dashboard/games/so-z-topish": "gameSozTopish",
  "/dashboard/games/krossvord": "gameKrossvord",
  "/admin": "admin",
  "/admin/users": "adminUsers",
  "/admin/schools": "adminSchools",
  "/admin/feedback": "adminFeedback",
  "/admin/audit": "adminAudit",
  "/admin/ai": "adminAi",
  "/admin/settings": "adminSettings",
};
