import type { FeedbackItem } from "./useFeedbackStore";

/* Fikr-mulohaza doskasining namunaviy fikrlari — doskani "tirik" koʻrsatish
   uchun, faqat ilk yuklashda ishlatiladi. Sanalar joriy davrga (2026 yoz)
   yaqin. Seed foydalanuvchining oʻzi yozgan fikr emas (isMine yoʻq). */

export const SEED_FEEDBACK: FeedbackItem[] = [
  {
    id: "seed-1",
    body:
      "Har kuni har bir oʻquvchini alohida belgilash koʻp vaqt oladi. «Hammasi keldi» tugmasi boʻlsa, faqat kelmaganlarni oʻzgartirardim.",
    category: "taklif",
    status: "jarayonda",
    author: "Nodira Karimova",
    authorInitials: "NK",
    createdAt: "2026-06-18T09:12:00.000Z",
    reactions: [
      { emoji: "❤️", count: 42, mine: false },
      { emoji: "👍", count: 12, mine: false },
    ],
    replies: [
      {
        id: "r-1a",
        author: "Ustozona jamoasi",
        isOfficial: true,
        body: "Ajoyib taklif! Kelgusi yangilanishga rejalashtirdik. Rahmat, Nodira.",
        createdAt: "2026-06-20T14:03:00.000Z",
      },
      {
        id: "r-1b",
        author: "Nodira Karimova",
        isOfficial: false,
        body: "Ajoyib, intiqlik bilan kutamiz! Rahmat.",
        createdAt: "2026-06-20T15:10:00.000Z",
        parentId: "r-1a",
      },
    ],
  },
  {
    id: "seed-2",
    body:
      "Telefonda jurnalga baho kiritganimda roʻyxat boshiga qaytib ketadi va qayerda qolganimni topolmayman.",
    category: "xato",
    status: "jarayonda",
    author: "Sardor Yusupov",
    authorInitials: "SY",
    createdAt: "2026-06-25T06:40:00.000Z",
    reactions: [{ emoji: "❤️", count: 17, mine: false }],
    replies: [
      {
        id: "r-2a",
        author: "Ustozona jamoasi",
        isOfficial: true,
        body: "Muammoni takrorlay oldik, tuzatish ustida ishlyapmiz. Xabaringiz uchun rahmat!",
        createdAt: "2026-06-26T10:15:00.000Z",
      },
    ],
  },
  {
    id: "seed-3",
    body: "Haftalik dars jadvalini PDF qilib chop etish imkoni boʻlsa — chiroyli chiqarib, oʻqituvchilar xonasiga osib qoʻyardik.",
    category: "taklif",
    status: "jarayonda",
    author: "Malika Toʻxtayeva",
    authorInitials: "MT",
    createdAt: "2026-06-28T11:20:00.000Z",
    reactions: [{ emoji: "❤️", count: 23, mine: false }],
    replies: [],
  },
  {
    id: "seed-4",
    body: "Kechqurun ishlaganda oq ekran koʻzni charchatadi. Qorongʻu rejim boʻlsa juda yaxshi boʻlardi.",
    category: "taklif",
    status: "bajarildi",
    author: "Jasur Rahimov",
    authorInitials: "JR",
    createdAt: "2026-05-30T18:05:00.000Z",
    reactions: [
      { emoji: "❤️", count: 58, mine: true },
      { emoji: "🔥", count: 15, mine: true },
      { emoji: "🎉", count: 6, mine: false },
    ],
    replies: [
      {
        id: "r-4a",
        author: "Ustozona jamoasi",
        isOfficial: true,
        body: "Qorongʻu rejim endi Sozlamalar boʻlimida mavjud. Sinab koʻring!",
        createdAt: "2026-06-02T08:00:00.000Z",
      },
      {
        id: "r-4b",
        author: "Jasur Rahimov",
        isOfficial: false,
        body: "Zoʻr, rahmat! Endi kechqurun ishlash ancha qulay.",
        createdAt: "2026-06-02T09:15:00.000Z",
        parentId: "r-4a",
      },
      {
        id: "r-4c",
        author: "Ustozona jamoasi",
        isOfficial: true,
        body: "Yoqqani juda xursandmiz! 🌙",
        createdAt: "2026-06-02T10:00:00.000Z",
        parentId: "r-4a",
      },
    ],
  },
  {
    id: "seed-5",
    body: "Qaydlarni ota-onaga qanday yetkazsam boʻladi? Telegram yoki SMS orqali ulash imkoni boʻlsa.",
    category: "savol",
    status: "yangi",
    author: "Gulnora Ergasheva",
    authorInitials: "GE",
    createdAt: "2026-07-01T07:30:00.000Z",
    reactions: [{ emoji: "❤️", count: 9, mine: false }],
    replies: [],
  },
  {
    id: "seed-6",
    body: "Oʻquv yili tugagach eski sinflarni bittalab arxivlash uzoq. Bir nechtasini belgilab, birdan arxivlash imkoni boʻlsa.",
    category: "taklif",
    status: "yangi",
    author: "Rustam Aliyev",
    authorInitials: "RA",
    createdAt: "2026-06-29T13:45:00.000Z",
    reactions: [{ emoji: "❤️", count: 14, mine: false }],
    replies: [],
  },
  {
    id: "seed-7",
    body: "Koʻp mavzu qoʻshilgan sinfda Standartlar sahifasi 5-6 soniya ochiladi. Sekinlashib qoldi.",
    category: "xato",
    status: "jarayonda",
    author: "Dilshoda Nazarova",
    authorInitials: "DN",
    createdAt: "2026-06-27T15:10:00.000Z",
    reactions: [{ emoji: "❤️", count: 6, mine: false }],
    replies: [],
  },
  {
    id: "seed-8",
    body: "Bir xil darsni har hafta qayta kiritmaslik uchun «har haftada takrorlansin» varianti kerak.",
    category: "taklif",
    status: "jarayonda",
    author: "Oybek Sultonov",
    authorInitials: "OS",
    createdAt: "2026-06-22T09:00:00.000Z",
    reactions: [
      { emoji: "❤️", count: 31, mine: false },
      { emoji: "🙏", count: 4, mine: false },
    ],
    replies: [],
  },
  {
    id: "seed-9",
    body: "Baholarni Excel (xlsx) qilib yuklab olish kerak — direksiya soʻrayapti, hozir faqat ekranda koʻrish mumkin.",
    category: "taklif",
    status: "yangi",
    author: "Feruza Qodirova",
    authorInitials: "FQ",
    createdAt: "2026-07-01T12:00:00.000Z",
    reactions: [{ emoji: "❤️", count: 11, mine: false }],
    replies: [],
  },
  {
    id: "seed-10",
    body: "Hamkasbim rus tilida ishlaydi. Interfeys tilini oʻzgartirish imkoni bormi?",
    category: "savol",
    status: "rad",
    author: "Kamola Yoʻldosheva",
    authorInitials: "KY",
    createdAt: "2026-06-15T10:25:00.000Z",
    reactions: [{ emoji: "❤️", count: 4, mine: false }],
    replies: [
      {
        id: "r-10a",
        author: "Ustozona jamoasi",
        isOfficial: true,
        body: "Hozircha faqat oʻzbek tili qoʻllab-quvvatlanadi. Rus tili rejalarimizda bor, lekin yaqin vaqtda emas.",
        createdAt: "2026-06-16T09:40:00.000Z",
      },
    ],
  },
  {
    id: "seed-11",
    body:
      "Dars rejalashtiruvchi ishimni ancha yengillashtirdi — hafta rejasini endi 10 daqiqada tuzib qoʻyaman. Jamoaga rahmat!",
    category: "maqtov",
    status: "yangi",
    author: "Zulfiya Hamidova",
    authorInitials: "ZH",
    createdAt: "2026-06-30T16:20:00.000Z",
    reactions: [
      { emoji: "❤️", count: 19, mine: false },
      { emoji: "😍", count: 5, mine: false },
    ],
    replies: [],
  },
  {
    id: "seed-12",
    body:
      "Qorongʻu rejim juda chiroyli chiqibdi, kechki ishlashda koʻz charchamayapti. Dizaynerlarga rahmat!",
    category: "maqtov",
    status: "yangi",
    author: "Bekzod Tursunov",
    authorInitials: "BT",
    createdAt: "2026-06-24T19:05:00.000Z",
    reactions: [{ emoji: "❤️", count: 8, mine: false }],
    replies: [
      {
        id: "r-12a",
        author: "Ustozona jamoasi",
        isOfficial: true,
        body: "Rahmat, Bekzod! Bunday soʻzlar jamoaga ilhom beradi.",
        createdAt: "2026-06-25T08:30:00.000Z",
      },
    ],
  },
];
