export { default as Dialog01 } from './dialog-01';
export { default as Dialog02 } from './dialog-02';
export { default as Dialog03 } from './dialog-03';
export { default as Dialog04 } from './dialog-04';
export { default as Dialog05 } from './dialog-05';
export { default as Dialog06 } from './dialog-06';
export { default as Dialog07 } from './dialog-07';
export { default as Dialog08 } from './dialog-08';
export { default as Dialog09 } from './dialog-09';
